### ISSUE TITLE
Animation tab

### ISSUE THREAD

**Issue by Legends** [ChromeDevTools/awesome-chrome-devtools#106]
If the devtools toolbar height is not heigh enough I cannot click the animation square because it is hidden by the animated gif:

There are two animations: first is visible, the second one is hidden by the animated gif and therefore not clickable, in order to execute a live preview.

![image](https://user-images.githubusercontent.com/966368/73477026-c013d480-4393-11ea-9d79-d1de54eeb149.png)

**It would be nice if one could deactivate the gif previews.**

**Comment by Garbee** [comment]
Bug reports should go on the [Chromium Issue Tracker](https://crbug.com/new) against the DevTools area.
