### ISSUE TITLE
Devtools cpuprofile parser

### ISSUE THREAD

**Issue by chrisruk** [ChromeDevTools/awesome-chrome-devtools#110]
Hi,

I've just been looking through your very useful list of tools, I'm just wondering though,
if you've ever come across something to process a cpuprofile file from devtools?

I mean a script that loads the same JSON format as is saved by the Profile tab of devtools and is capable of generating Start time, Self time, Total time, for specific function calls from the cpuprofile file (data which you can normally see in the Event Log of the Profile tab).

Cheers!

**Comment by paulirish** [comment]
three off the top of my head... 

https://github.com/jlfwong/speedscope/blob/66a9e5d1cf6be5dcdc49f651f290f95c7d007cd3/src/import/chrome.ts#L200

https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/front_end/sdk/CPUProfileDataModel.js

https://github.com/microsoft/vscode-js-profile-visualizer

there are definitely more.
