### ISSUE TITLE
Where can I find some detailed information about the "rendering" dev tool?

### ISSUE THREAD

**Issue by coolinker** [ChromeDevTools/awesome-chrome-devtools#116]
I'm interested in developing a tool(extension or dev tool) which can detect the dom update (dom painting), similar to the "rendering" chrome dev tool. 
I'm new to chome development, and not sure where can I get the document I need.

Thanks.
Jake

**Comment by sidorares** [comment]
Have a look at [Overlay](https://chromedevtools.github.io/devtools-protocol/tot/Overlay/) and [LayoutTree](https://chromedevtools.github.io/devtools-protocol/tot/LayerTree/#event-layerPainted)

**Comment by sidorares** [comment]
I'd recommend forum like google-chrome-developer-tools@googlegroups.com for questions like your @coolinker

**Comment by coolinker** [comment]
Great. Thanks @sidorares
