### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by rollin505** [ChromeDevTools/awesome-chrome-devtools#122]

**Comment by dasa376** [comment]
function add_contact_links ( $text ) {   $text .= '   <hr><p><a href="' . get_permalink($post) . '#commentform">Add a comment to the post, or <a href="mailto:admin@example.com?subject=In%20reply%20to%20%22' . str_replace(' ', '%20', get_the_title()) . '%22">email a reply</a>.</p>';   return $text; } add_filter('the_content_feed', 'add_contact_links');
