### ISSUE TITLE
Add Reason of "Recalculate Style"

### ISSUE THREAD

**Issue by glebmachine** [ChromeDevTools/awesome-chrome-devtools#128]
Hi, thank you for great devtools!

It would be nice to have information about what exact Elements and CSS Properties has been modified and become reason of "Recalculate Style" process
![image](https://user-images.githubusercontent.com/1610882/144101774-e140ef31-6a22-4c8f-9b68-7da63fe82478.png)

This will provide fine grade performance investigation experience)

**Comment by paulirish** [comment]
This isn't the place for feature requests.. but.. I do know the answer so you get it for free.

There's a hidden experiment called "invalidation tracking"

![image](https://user-images.githubusercontent.com/39191/144102565-5dce8d4d-0f9d-4b01-8ea0-7f090f47e3ff.png)

it's an old experiment that never shipped. (but surprisingly it does still seem to work.)


![image](https://user-images.githubusercontent.com/39191/144102849-6491bb32-c402-498a-ba4d-2f7bbf5c27bd.png)
![image](https://user-images.githubusercontent.com/39191/144102877-38ebdd0c-fa41-4a73-8b86-980477db7f8a.png)

it lists the invalidations aka _changes that necessitate recomputing style or layout_.

Those mutations happened somewhere between this recalcstyle and the previous one. But it wont tell you where.

That said, it's pretty helpful!

**Comment by glebmachine** [comment]
@paulirish jeez, you awesome, thank you!)

**Comment by bartzy** [comment]
> it's an old experiment that never shipped. (but surprisingly it does still seem to work.)

@paulirish Why didn't it ship eventually? Seems extremely helpful!
