### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by Garbee** [ChromeDevTools/awesome-chrome-devtools#13]
Since it is under the ChromeDevTools org we could just call it `awesome`. That would net us the beautiful `https://github.com/ChromeDevTools/awesome` URL. ;)

**Comment by derimagia** [comment]
Would be neat but an issue I see is when people fork this it'll go to their <name>/awesome, which could be annoying for some people.

**Comment by Garbee** [comment]
People can re-name if they want to keep a copy long-term as a fork.

But, if you are using a fork as a "backup", then you're using it wrong.

And doesn't GH do something if a name collision happens, like ask you to rename? /me goes to test this one.

**Comment by derimagia** [comment]
Not as a backup - I know how forks work and how to rename them, was simply a small point. I either use github's interface or use [ghq](https://github.com/motemen/ghq) and hub to fork so it's just easier to not have to rename when it's just simple markdown.

Thanks for the clarification on auto-rename. I'd support switching it despite the small issue

**Comment by paulirish** [comment]
i was pretty much following the pattern of the other awesome repos and i typically see the full name there. 

bummer that it duplicates but i'd prefer it.   the new `/perfs/audits` repo that we made i'm already starting to feel a little weird about the contextlessness of the name. :)

**Comment by paulirish** [comment]
so i'm -1 on rename but am flexible if other folks also think it'd be better

**Comment by Garbee** [comment]
Nah, that's cool. Just a thought to get a prettier/less redundant URL.
