### ISSUE TITLE
Add devtoolsecrets.com website ?

### ISSUE THREAD

**Issue by ThomasG77** [ChromeDevTools/awesome-chrome-devtools#33]
Do you thing it's worth adding http://devtoolsecrets.com?
Why this interrogation? Because this is not only about Chrome but all browsers debuggers.
Depending on feedback, I will submit it after discussion where to insert the content.

**Comment by Garbee** [comment]
Personally I wouldn't add it until the content is updated to reflect the
current tool states. The instructions it provides on finding things are old.

**Comment by paulirish** [comment]
yeah i think it's a bit old at this point (unfortunately). it's a well done guide though
