### ISSUE TITLE
Performance Section

### ISSUE THREAD

**Issue by stefanjudis** [ChromeDevTools/awesome-chrome-devtools#35]
Are you folks up for a perf section? `spof-o-matic` is immediately coming to my mind. :)

**Comment by Garbee** [comment]
That extension is more about potential site reliability over performance.

**Comment by paulirish** [comment]
spof o matic isn't directly related to the devtools, so i'd hesitate to add it.

beyond that, i'm interested in a perf section yes.

closing, but feel free to PR or open any new issues for discussion..
