### ISSUE TITLE
RemoteDebug MDNS Spec

### ISSUE THREAD

**Issue by derimagia** [ChromeDevTools/awesome-chrome-devtools#6]
I wanted to get peoples thoughts on: https://github.com/RemoteDebug/remotedebug-mdns-spec

It would be nice to provide a standard way for mdns to interact with remote debuggers.

I didn't submit a pull request because I'm not sure if it's a good thing for the list.

**Comment by paulirish** [comment]
I think it's great stuff though on the edges, and probably not for the list.

tbh it'd be valuable to have a vendor neutral browser devtools mailing list.. and this'd be perfect for that.

**Comment by samccone** [comment]
@derimagia yay +1 to land this -- I can open the PR for you if you would like?

**Comment by auchenberg** [comment]
There's already a [RemoteDebug mailing list](https://groups.google.com/forum/#!forum/remotedebug), which currently is quote dead. 

I'm open to suggestions, as we need to get the communication flowing :)

**Comment by paulirish** [comment]
I've added remotedebug to the list in b1eb1a2826a461d5afc1454f86e7a886cf42f0f3 so I think that'll best serve as a pointer to the MDNS effort.

**Comment by auchenberg** [comment]
I've updated RemoteDebug.org to include the MDNS spec, http://remotedebug.org/specifications/

Thanks @paulirish!
