### ISSUE TITLE
Add pyppeteer and puppeteer-sharp

### ISSUE THREAD

**Issue by lanzorg** [ChromeDevTools/awesome-chrome-devtools#74]
Could you add these libraries? ;)
- https://github.com/miyakogi/pyppeteer
- https://github.com/kblok/puppeteer-sharp

**Comment by kentvuong99199** [comment]
Ruko input TV to smart vision can file channel mint . so good for life and some wrong to let program control human mind , some one can't know my thing and let my to expect. My hand
