### ISSUE TITLE
Is there any backend library?

### ISSUE THREAD

**Issue by Fndroid** [ChromeDevTools/awesome-chrome-devtools#82]
I want to build a tool to debug scripts that run on my phone remotely.

Right now I am using nodejs as a proxy. My mobile APP sends all logs to nodejs then nodejs echo them with console.log() method so that I could inspect logs using Chrome Devtools Inspector with command node index.js --inspect.

But If I want to send command from Chrome Devtoos back to my app, the proxy way will not be able to do that because I can't get that input.

So is there any library that implement Chrome Devtools Protocol backend can help me with my tools.

I tried to find but all of the libraries are frontend like Chrome Devtools.

**Comment by paulirish** [comment]
Not sure what sort of tool you want. :/

Are you dealing with an android webview? You can [debug those with Chrome DevTools frontend](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews).

But it sounds like you don't want to use that UI?

It's possible to use the protocol to evaluate javascript inside a webview (and collect the output, etc). But it's a decent amount of work, and you end up with a small subset of what the devtools frontend support already gives you.

**Comment by Fndroid** [comment]
@paulirish 

Thank you for your reply. 

I am working on building a logger that receive logs from an iOS application and I want to print those logs in Chrome Devtools or other Debuggers.

And I also want to receive commands from Chrome Devtools Console Tab so that I can ``eval()`` them on my iOS application with a javascript runtime.

So I think maybe some backend(websocket and http server wrapped) libraries could help me to communicate with Chrome Devtools.

**Comment by sidorares** [comment]
@Fndroid my [crmux ](https://github.com/sidorares/crmux) is basically a proxy, have a look at server part of it, you can add a code to modify packets before sending to back to debugger frontend or debuggee. The core protocol itself is very simple, just json messages over websocket
